<footer><footer class="text-center text-white fixed-bottom" style="background-color: rgba(var(--bs-tertiary-bg-rgb),var(--bs-bg-opacity))!important;">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);color: var(--bs-body-color);">
            Market Challenger v1.0 -
            <a class="text-decoration-none" href="https://github.com/rafakoller/marketchallenger" style="color: var(--bs-body-color);">RafaKoller</a>
        </div>
    </footer>

</footer>